package log

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/cloudwego/kitex/pkg/klog"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

const (
	timestampFormat = "2006-01-02 15:04:05.000"
	placeholder     = "-"
)

// Frames from these packages are logging plumbing, never the caller worth reporting.
var plumbingPrefixes = []string{
	reflect.TypeFor[textLogger]().PkgPath() + ".",
	"github.com/cloudwego/kitex/pkg/klog.",
	"github.com/cloudwego/hertz/pkg/common/hlog.",
}

var bufPool = sync.Pool{New: func() any { return new([]byte) }}

// textLogger writes one line per record:
//
//	time level pid gid trace_id caller {custom fields} : message
type textLogger struct {
	mu        sync.Mutex
	out       io.Writer
	threshold atomic.Int32 // Level
	sinks     atomic.Pointer[[]Sink]
}

func newTextLogger(out io.Writer) *textLogger {
	return &textLogger{out: out}
}

func (l *textLogger) SetLevel(level klog.Level) {
	l.threshold.Store(int32(fromKlogLevel(level)))
}

func (l *textLogger) SetOutput(w io.Writer) {
	l.mu.Lock()
	l.out = w
	l.mu.Unlock()
}

func (l *textLogger) addSink(s Sink) {
	for {
		old := l.sinks.Load()
		next := append(cloneSinks(old), s)
		if l.sinks.CompareAndSwap(old, &next) {
			return
		}
	}
}

func cloneSinks(p *[]Sink) []Sink {
	if p == nil {
		return nil
	}
	return append([]Sink(nil), *p...)
}

func (l *textLogger) enabled(level Level) bool {
	return level >= Level(l.threshold.Load())
}

// log formats with Sprintf when formatted and Sprint otherwise, only once the record
// passes the level threshold.
func (l *textLogger) log(ctx context.Context, kl klog.Level, formatted bool, format string, v []any) {
	level := recordLevel(kl)
	if !l.enabled(level) {
		return
	}
	var text string
	if formatted {
		text = fmt.Sprintf(format, v...)
	} else {
		text = fmt.Sprint(v...)
	}
	if ctx == nil {
		ctx = context.Background()
	}
	spanCtx := trace.SpanContextFromContext(ctx)
	if level >= LevelError {
		if span := trace.SpanFromContext(ctx); span.IsRecording() {
			span.SetStatus(codes.Error, "")
			span.RecordError(errors.New(text), trace.WithStackTrace(true))
		}
	}

	bp := bufPool.Get().(*[]byte)
	b := time.Now().AppendFormat((*bp)[:0], timestampFormat)
	b = append(b, ' ')
	b = append(b, level.String()...)
	b = append(b, ' ')
	b = append(b, pid...)
	b = append(b, ' ')
	b = append(b, GetGID()...)
	b = append(b, ' ')
	if spanCtx.HasTraceID() {
		b = append(b, spanCtx.TraceID().String()...)
	} else {
		b = append(b, placeholder...)
	}
	b = append(b, ' ')
	b = appendCaller(b)
	b = append(b, ' ')
	b = appendFields(b, GetAllCustomFields(ctx))
	b = append(b, " : "...)
	b = append(b, text...)
	b = append(b, '\n')

	l.mu.Lock()
	_, _ = l.out.Write(b)
	l.mu.Unlock()
	*bp = b
	bufPool.Put(bp)

	if sinks := l.sinks.Load(); sinks != nil {
		for _, s := range *sinks {
			s.Emit(ctx, level, text)
		}
	}
	if kl == klog.LevelFatal {
		os.Exit(1)
	}
}

func appendCaller(b []byte) []byte {
	var pcs [16]uintptr
	frames := runtime.CallersFrames(pcs[:runtime.Callers(2, pcs[:])])
	for {
		frame, more := frames.Next()
		if frame.File != "<autogenerated>" && !isPlumbing(frame.Function) {
			b = append(b, frame.File...)
			b = append(b, ':')
			return strconv.AppendInt(b, int64(frame.Line), 10)
		}
		if !more {
			return append(b, placeholder...)
		}
	}
}

func isPlumbing(function string) bool {
	for _, prefix := range plumbingPrefixes {
		if strings.HasPrefix(function, prefix) {
			return true
		}
	}
	return false
}

func appendFields(b []byte, fields map[string]string) []byte {
	if len(fields) == 0 {
		return append(b, "{}"...)
	}
	encoded, err := json.Marshal(fields)
	if err != nil {
		return append(b, "{}"...)
	}
	return append(b, encoded...)
}

func (l *textLogger) Trace(v ...any)  { l.log(context.Background(), klog.LevelTrace, false, "", v) }
func (l *textLogger) Debug(v ...any)  { l.log(context.Background(), klog.LevelDebug, false, "", v) }
func (l *textLogger) Info(v ...any)   { l.log(context.Background(), klog.LevelInfo, false, "", v) }
func (l *textLogger) Notice(v ...any) { l.log(context.Background(), klog.LevelNotice, false, "", v) }
func (l *textLogger) Warn(v ...any)   { l.log(context.Background(), klog.LevelWarn, false, "", v) }
func (l *textLogger) Error(v ...any)  { l.log(context.Background(), klog.LevelError, false, "", v) }
func (l *textLogger) Fatal(v ...any)  { l.log(context.Background(), klog.LevelFatal, false, "", v) }

func (l *textLogger) Tracef(format string, v ...any) {
	l.log(context.Background(), klog.LevelTrace, true, format, v)
}
func (l *textLogger) Debugf(format string, v ...any) {
	l.log(context.Background(), klog.LevelDebug, true, format, v)
}
func (l *textLogger) Infof(format string, v ...any) {
	l.log(context.Background(), klog.LevelInfo, true, format, v)
}
func (l *textLogger) Noticef(format string, v ...any) {
	l.log(context.Background(), klog.LevelNotice, true, format, v)
}
func (l *textLogger) Warnf(format string, v ...any) {
	l.log(context.Background(), klog.LevelWarn, true, format, v)
}
func (l *textLogger) Errorf(format string, v ...any) {
	l.log(context.Background(), klog.LevelError, true, format, v)
}
func (l *textLogger) Fatalf(format string, v ...any) {
	l.log(context.Background(), klog.LevelFatal, true, format, v)
}

func (l *textLogger) CtxTracef(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelTrace, true, format, v)
}
func (l *textLogger) CtxDebugf(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelDebug, true, format, v)
}
func (l *textLogger) CtxInfof(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelInfo, true, format, v)
}
func (l *textLogger) CtxNoticef(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelNotice, true, format, v)
}
func (l *textLogger) CtxWarnf(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelWarn, true, format, v)
}
func (l *textLogger) CtxErrorf(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelError, true, format, v)
}
func (l *textLogger) CtxFatalf(ctx context.Context, format string, v ...any) {
	l.log(ctx, klog.LevelFatal, true, format, v)
}
